### PR TITLE
delete XCTAutomationSupport

### PR DESCRIPTION
**Pull request by chao2318**

### CODE REVIEW

**Comment by geron-cn** [comment]
resolve Xcode14 issue
#103  #106 #105

**Review by geron-cn — APPROVED** [review]
Resolved Xcode14 issue

**Comment by nicole1010** [comment]
占坑waiting.

**Comment by 1914049892** [comment]
Has commit into the main  branch?

**Comment by songweilongcode12** [comment]
ios fastbot 啥时候支持白名单策略

**Pull request merged**
